[subsection {Changes for version 1.1}]

[para] In detail:

[list_begin enumerated]
[comment {- - -- --- ----- -------- ------------- ---------------------}]

[enum] Bumped minimum version of Tcl required to use the package to 8.6.

[enum] Reworked to be [strong {usable with Tcl 9}], while keeping ability to build against 8.6.

[enum] Added references to the RHash project, as the origin of the majority of the hash implementations.

[enum] Various small fixes (Mismatched, out-of-date version numbers, build configuration, doc typos, ...).

[comment {- - -- --- ----- -------- ------------- ---------------------}]
[list_end]
