[subsection {Changes for version 1.0}]

[para] In detail:

[list_begin enumerated]
[comment {- - -- --- ----- -------- ------------- ---------------------}]


[enum] This is the first release of [const Ankh] considered to be
       feature complete.

[enum] All hash commands now accept two options, [option -offset] and
       [option -length]. With these the user can control the slice of
       the input to hash.

[comment {- - -- --- ----- -------- ------------- ---------------------}]
[list_end]
