
[comment { - - -- --- ----- -------- ------------- --------------------- }]

[vset PROJECT    Ankh]
[vset PROJECT_lc ankh]

[vset VERSION    1.0]
[comment {
    See also
    - tests/version.test
    - ankh.tcl
}]

[vset logo [image logo [vset PROJECT]]]

[comment { - - -- --- ----- -------- ------------- --------------------- }]

[vset project/chisel/url   https://chiselapp.com/user/andreas_kupries/repository/ankh]
[vset project/core/url     https://core.tcl-lang.org/akupries/ankh]
[vset project/github/url   https://github.com/andreas-kupries/ankh]

[vset activestate      [uri https://www.activestate.com ActiveState]]
[vset activetcl        [uri https://www.activestate.com/activetcl ActiveTcl]]
[vset core/tcl         [uri https://core.tcl-lang.org/tcl]]
[vset critcl           [uri https://github.com/andreas-kupries/critcl Critcl]]
[vset fossil           [uri https://www.fossil-scm.org               {Fossil SCM}]]
[vset fossil/get       [uri https://www.fossil-scm.org/download.html {download page}]]
[vset kettle/chisel    [uri https://chiselapp.com/user/andreas_kupries/repository/Kettle]]
[vset kettle/core      [uri https://core.tcl-lang.org/akupries/kettle]]
[vset kettle/github    [uri https://github.com/andreas-kupries/kettle]]
[vset kettle/iguide    [uri https://core.tcl-lang.org/akupries/kettle/doc/trunk/embedded/md/doc/files/kettle_installer.md]]

[vset project/chisel   [uri [vset project/chisel/url]]]
[vset project/core     [uri [vset project/core/url]]]
[vset project/github   [uri [vset project/github/url]]]

[vset project/track    [uri https://core.tcl-lang.org/akupries/ankh {Ankh Tracker}]]
[vset rhash            [uri https://github.com/rhash/RHash RHash]]
[vset tcllib/core      [uri https://core.tcl-lang.org/tcllib Tcllib]]
[vset teapot           [uri https://teapot.activestate.com]]

[comment { - - -- --- ----- -------- ------------- --------------------- }]
