---
abstract: 'Library for computing message digests and magnet links'
author:
  - 'Aleksey Kravchenko'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 6.84, CPAN::Meta::Converter version 2.133380'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Crypt-Rhash
no_index:
  directory:
    - t
    - inc
requires: {}
resources:
  bugtracker: https://github.com/rhash/RHash/issues
  homepage: http://rhash.sf.net/
  license: https://github.com/rhash/RHash/blob/master/COPYING
  repository: https://github.com/rhash/RHash
version: 1.00
